database.url = jdbc:mysql://host.docker.internal:3306/aion_gs?serverTimezone=${gameserver.timezone}&characterEncoding=UTF-8
database.user = root
database.password = Farmer598!

# Public address advertised to game clients.
gameserver.network.client.connect_address = 173.188.215.212:7777
gameserver.network.login.address = login:9014
gameserver.network.chat.address = chat:9021