#!/bin/bash
# Writes the LoginServer config override (myls.properties) from environment, then launches.
set -e

cat > /app/login-server/config/myls.properties <<EOF
# AUTO-GENERATED by the docker entrypoint from environment / .env — do not edit by hand.
database.url = jdbc:mysql://${DB_HOST:-mysql}:${DB_PORT:-3306}/aion_ls?characterEncoding=UTF-8
database.user = ${DB_USER:-root}
database.password = ${DB_PASSWORD:-aion}

# Bind addresses inside the container (host port mapped by compose for the client port).
loginserver.network.client.socket_address = 0.0.0.0:2106
loginserver.network.gameserver.socket_address = 0.0.0.0:9014
EOF

cd /app
exec dotnet Aion.LoginServer.dll
