using Aion.GameServer.Services;

namespace Aion.GameServer.Tests;

public sealed class PlayerProtectionActiveTaskStopTriggerJavaTraceArtifactDirectoryReportServiceTests
{
	[Fact]
	public void Create_MissingDirectoryReportsBlockedReadiness()
	{
		var missing = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N"));

		var report = PlayerProtectionActiveTaskStopTriggerJavaTraceArtifactDirectoryReportService.Create(missing);

		Assert.Equal(PlayerProtectionActiveTaskStopTriggerJavaTraceArtifactDirectoryStatus.MissingDirectory, report.Status);
		Assert.False(report.HasGeneratedJavaArtifacts);
		Assert.False(report.ReadyForRuntimeComparison);
		Assert.Empty(report.Files);
	}

	[Fact]
	public void Create_EmptyDirectoryReportsNoArtifacts()
	{
		var directory = CreateTempDirectory();
		try
		{
			var report = PlayerProtectionActiveTaskStopTriggerJavaTraceArtifactDirectoryReportService.Create(directory);

			Assert.Equal(PlayerProtectionActiveTaskStopTriggerJavaTraceArtifactDirectoryStatus.NoArtifacts, report.Status);
			Assert.False(report.HasGeneratedJavaArtifacts);
			Assert.False(report.ReadyForRuntimeComparison);
		}
		finally
		{
			Directory.Delete(directory, recursive: true);
		}
	}

	[Fact]
	public void Create_ValidArtifactReportsShapeValidButNotRuntimeReady()
	{
		var directory = CreateTempDirectory();
		try
		{
			File.WriteAllText(Path.Combine(directory, "valid.json"), RepresentativeArtifactJson);

			var report = PlayerProtectionActiveTaskStopTriggerJavaTraceArtifactDirectoryReportService.Create(directory);

			Assert.Equal(PlayerProtectionActiveTaskStopTriggerJavaTraceArtifactDirectoryStatus.AllArtifactsShapeValid, report.Status);
			Assert.True(report.HasGeneratedJavaArtifacts);
			Assert.False(report.ReadyForRuntimeComparison);
			Assert.Single(report.Files);
			Assert.True(report.Files[0].ValidationReport.IsValidSchemaV1);
			var metadata = report.Files[0].ValidationReport.Metadata!;
			Assert.NotNull(metadata);
			Assert.Equal("directory-reader-validator-contract", metadata.Scenario);
			Assert.Single(metadata.TraceRows);
		}
		finally
		{
			Directory.Delete(directory, recursive: true);
		}
	}

	[Fact]
	public void Create_InvalidArtifactAggregatesValidationIssues()
	{
		var directory = CreateTempDirectory();
		try
		{
			File.WriteAllText(Path.Combine(directory, "valid.json"), RepresentativeArtifactJson);
			File.WriteAllText(Path.Combine(directory, "invalid.json"), RepresentativeArtifactJson.Replace("\"schemaVersion\": 1", "\"schemaVersion\": 2", StringComparison.Ordinal));

			var report = PlayerProtectionActiveTaskStopTriggerJavaTraceArtifactDirectoryReportService.Create(directory);

			Assert.Equal(PlayerProtectionActiveTaskStopTriggerJavaTraceArtifactDirectoryStatus.InvalidArtifacts, report.Status);
			Assert.True(report.HasGeneratedJavaArtifacts);
			Assert.False(report.ReadyForRuntimeComparison);
			Assert.Equal(2, report.Files.Count);
			Assert.Contains(report.Files, file => file.ValidationReport.Issues.Any(issue => issue.Code == PlayerProtectionActiveTaskStopTriggerJavaTraceArtifactValidationIssueCode.UnsupportedSchemaVersion));
			Assert.Contains(report.Files, file => !file.ValidationReport.IsValidSchemaV1 && file.ValidationReport.Metadata == null);
		}
		finally
		{
			Directory.Delete(directory, recursive: true);
		}
	}

	private static string CreateTempDirectory()
	{
		var directory = Path.Combine(Path.GetTempPath(), $"protection-stop-trigger-{Guid.NewGuid():N}");
		Directory.CreateDirectory(directory);
		return directory;
	}

	private const string RepresentativeArtifactJson = """
		{
		  "schemaVersion": 1,
		  "javaCommit": "abcdef1",
		  "scenario": "directory-reader-validator-contract",
		  "runtimeFacts": {
		    "serverFlavor": "java",
		    "packetName": "CM_TELEPORT_ANIMATION_DONE",
		    "playerObjectId": 1001,
		    "worldId": 301390000,
		    "expectedReturnReason": "animation_done_no_pending_runnable_teleport_task"
		  },
		  "javaSources": [
		    "CM_TELEPORT_ANIMATION_DONE.runImpl"
		  ],
		  "traces": [
		    {
		      "eventSeq": 0,
		      "phase": "teleport_task_remove",
		      "packetName": "CM_TELEPORT_ANIMATION_DONE",
		      "returnReason": "animation_done_no_pending_runnable_teleport_task",
		      "stopCalled": false,
		      "expectsStopProtectionCall": false,
		      "timestampIsParityKey": false,
		      "javaSourceFile": "CM_TELEPORT_ANIMATION_DONE.java",
		      "javaLine": 36,
		      "player": {
		        "objectId": 1001,
		        "spawned": false,
		        "flying": false,
		        "dead": false,
		        "protectionActiveBefore": true,
		        "protectionActiveAfter": true,
		        "visualStateBefore": ["BLINKING"],
		        "visualStateAfter": ["BLINKING"]
		      }
		    }
		  ],
		  "notes": [
		    "Representative directory reader fixture only; not generated by Java runtime."
		  ]
		}
		""";
}
