#!/usr/bin/env python3
"""
Faithful 1:1 generator for SM_SYSTEM_MESSAGE.

Parses game-server .../network/aion/serverpackets/SM_SYSTEM_MESSAGE.java (≈28.9k lines,
4099 generated STR_* static factory methods) and emits the C# parallel
dotnetConversion/.../Network/Aion/ServerPackets/SM_SYSTEM_MESSAGE.cs.

This is the literal Java truth (SCREAMING STR_ names, AionServerPacket base, Object[] params),
deliberately PARALLEL to the reworked SmSystemMessage : GameServerPacket (PascalCase, string[]
params) so there is no name collision and zero risk to the working build. The AionServerPacket
base + WriteC/WriteD/WriteS are the deferred NIO layer (red-tolerated on this branch).

Java->C# mappings: String->string, int->int, long->long, byte->sbyte, float->float; Object...->params object[];
chatType.getId()->GetId() (Model extension); sender.getObjectId()->GetObjectId(); writeC/D/S->WriteC/D/S;
writeImpl->WriteImpl; getId->GetId. Javadoc message text is preserved as a /* */ block (not /** */ XML doc,
to avoid XML-escaping the % / < / & in message strings).

Run: python scripts/parity/gen_sm_system_message.py
"""
import re
import sys
import io

JAVA = "game-server/src/com/aionemu/gameserver/network/aion/serverpackets/SM_SYSTEM_MESSAGE.java"
OUT = "dotnetConversion/src/Aion.GameServer/Network/Aion/ServerPackets/SM_SYSTEM_MESSAGE.cs"

TYPE_MAP = {"String": "string", "int": "int", "long": "long", "byte": "sbyte", "float": "float"}

# The 3 hand-written (non-uniform) factories: they take a Player and build complex args
# (getRace().getL10n(), position concat, AbyssRankEnum.getRankL10n, or delegate to a sibling).
# Faithfully hand-translated; injected after the generated uniform catalog.
SPECIAL_METHODS = """\
    /* %0's %1 has been activated. */
    public static SM_SYSTEM_MESSAGE STR_SKILL_ABYSS_SKILL_IS_FIRED(Player player, string skill)
    {
        return new SM_SYSTEM_MESSAGE(1390155, player.GetRace().GetL10n(), player.GetName(), "%SubZone:" + player.GetPosition().GetMapId() + " "
            + player.GetPosition().GetX() + " " + player.GetPosition().GetY() + " " + player.GetPosition().GetZ(), skill);
    }

    /* %0 %1 %2 has died in %3. */
    public static SM_SYSTEM_MESSAGE STR_ABYSS_ORDER_RANKER_DIE(Player victim)
    {
        return STR_ABYSS_ORDER_RANKER_DIE(victim, "%SubZone:" + victim.GetPosition().GetMapId() + " " + victim.GetPosition().GetX()
            + " " + victim.GetPosition().GetY() + " " + victim.GetPosition().GetZ());
    }

    /* %0 %1 %2 has died in %3. */
    public static SM_SYSTEM_MESSAGE STR_ABYSS_ORDER_RANKER_DIE(Player victim, string zoneName)
    {
        return new SM_SYSTEM_MESSAGE(1400023, victim.GetRace().GetL10n(), AbyssRankEnum.GetRankL10n(victim), victim.GetName(), zoneName);
    }

"""
SPECIAL_COUNT = 3

METHOD_RE = re.compile(
    r"public static SM_SYSTEM_MESSAGE (STR_\w+)\s*\((.*?)\)\s*\{\s*"
    r"return new SM_SYSTEM_MESSAGE\((.*?)\);\s*\}",
    re.S,
)
DOC_RE = re.compile(r"/\*\*(.*?)\*/", re.S)


def map_params(param_str: str) -> str:
    param_str = param_str.strip()
    if not param_str:
        return ""
    out = []
    for part in param_str.split(","):
        toks = part.split()
        jtype, name = toks[0], toks[1]
        ctype = TYPE_MAP.get(jtype)
        if ctype is None:
            raise SystemExit(f"Unknown param type '{jtype}' in '{part}'")
        out.append(f"{ctype} {name}")
    return ", ".join(out)


def clean_doc(doc: str) -> str:
    lines = []
    for ln in doc.splitlines():
        ln = ln.strip()
        if ln.startswith("*"):
            ln = ln[1:].strip()
        if ln:
            lines.append(ln)
    text = " ".join(lines).strip()
    return text.replace("*/", "* /")  # never terminate the block comment early


def main():
    with open(JAVA, "r", encoding="utf-8", newline="") as f:
        text = f.read()

    methods = list(METHOD_RE.finditer(text))
    if not methods:
        raise SystemExit("No STR_ methods matched - generator regex is stale")

    buf = io.StringIO()
    w = buf.write
    total_decls = len(re.findall(r"public static SM_SYSTEM_MESSAGE STR_\w+\s*\(", text))

    w("using Aion.GameServer.Model;\n")
    w("using Aion.GameServer.Model.GameObjects;\n")
    w("using Aion.GameServer.Network.Aion;\n")
    w("using Aion.GameServer.Utils.Stats;\n\n")
    w("namespace Aion.GameServer.Network.Aion.ServerPackets;\n\n")
    w("/// <summary>\n")
    w("/// Java parity: network/aion/serverpackets/SM_SYSTEM_MESSAGE (-Nemesiss-, EvilSpirit, Luno, Avol, Simple, Sarynth).\n")
    w("/// System message packet with the full generated catalog of STR_* factory methods (1:1 with the Java file).\n")
    w("/// GENERATED by scripts/parity/gen_sm_system_message.py - do not edit by hand. Parallel to the reworked\n")
    w("/// SmSystemMessage : GameServerPacket (no collision). AionServerPacket base + WriteC/WriteD/WriteS are the\n")
    w("/// deferred NIO layer (red-tolerated). Object... -> params object[]; String->string, byte->sbyte, etc.\n")
    w("/// </summary>\n")
    w("public sealed class SM_SYSTEM_MESSAGE : AionServerPacket\n{\n")

    prev_end = 0
    count = 0
    for m in methods:
        name, params, args = m.group(1), m.group(2), m.group(3)
        # nearest preceding javadoc, if any
        gap = text[prev_end:m.start()]
        docs = DOC_RE.findall(gap)
        doc_text = clean_doc(docs[-1]) if docs else None
        prev_end = m.end()

        # skip the hand-written non-uniform factories (Player param etc.) - injected separately
        if any(p.split()[0] not in TYPE_MAP for p in params.split(",") if p.strip()):
            continue

        csparams = map_params(params)
        csargs = re.sub(r"\s+", " ", args.strip())
        if doc_text:
            w(f"    /* {doc_text} */\n")
        w(f"    public static SM_SYSTEM_MESSAGE {name}({csparams})\n")
        w("    {\n")
        w(f"        return new SM_SYSTEM_MESSAGE({csargs});\n")
        w("    }\n\n")
        count += 1

    # the 3 hand-written specials
    w(SPECIAL_METHODS)
    count += SPECIAL_COUNT

    if count != total_decls:
        raise SystemExit(f"Method count mismatch: emitted {count} but Java declares {total_decls} STR_ factories")

    # fields + constructors + writeImpl + getId (faithful to the Java tail)
    w("    private int msgId;\n")
    w("    private byte chatType;\n")
    w("    private int senderObjId;\n")
    w("    private object[] @params;\n")
    w("    private string[] specialParams;\n\n")
    w("    public SM_SYSTEM_MESSAGE(int msgId, params object[] @params)\n")
    w("        : this(ChatType.GOLDEN_YELLOW, null, msgId, @params, new string[0])\n    {\n    }\n\n")
    w("    public SM_SYSTEM_MESSAGE(ChatType chatType, VisibleObject sender, int msgId, params object[] @params)\n")
    w("        : this(chatType, sender, msgId, @params, new string[0])\n    {\n    }\n\n")
    w("    public SM_SYSTEM_MESSAGE(ChatType chatType, VisibleObject sender, int msgId, object[] @params, params string[] specialParams)\n    {\n")
    w("        this.chatType = chatType.GetId();\n")
    w("        this.senderObjId = sender == null ? 0 : sender.GetObjectId();\n")
    w("        this.msgId = msgId;\n")
    w("        this.@params = @params == null ? new object[0] : @params;\n")
    w("        this.specialParams = specialParams;\n    }\n\n")
    w("    protected override void WriteImpl(AionConnection con)\n    {\n")
    w("        WriteC(chatType);\n")
    w("        WriteC(0x00); // to do for shoots text encoding (unk dialect)\n")
    w("        WriteD(senderObjId);\n")
    w("        WriteD(msgId);\n")
    w("        WriteC(@params.Length);\n")
    w("        foreach (object param in @params)\n")
    w("            WriteS(param == null ? null : param.ToString());\n\n")
    w("        WriteC(specialParams.Length);\n")
    w("        foreach (string param in specialParams)\n        {\n            WriteS(param);\n        }\n    }\n\n")
    w("    public int GetId()\n    {\n        return msgId;\n    }\n")
    w("}\n")

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(buf.getvalue())

    print(f"Generated {OUT}: {count} STR_ factory methods")


if __name__ == "__main__":
    main()
