using System;
using System.Collections;
using System.Collections.Generic;
using Aion.GameServer.Model;
using Aion.GameServer.Model.Items.Storage;

namespace Aion.GameServer.Model.Account;

/// <summary>
/// Java parity: model/account/Account (SoulKeeper, cura). Represents a game account (id, name, AccountTime,
/// list of PlayerAccountData for char-selection). implements Iterable→IEnumerable&lt;PlayerAccountData&gt;;
/// signed byte→sbyte; java.sql.Timestamp→DateTimeOffset?; Map.put return-old-value→TryGetValue+assign;
/// equals/hashCode→Equals/GetHashCode. Storage/AccountTime/CharacterPasskey/PassportsList red-tolerated.
/// </summary>
public class Account : IEnumerable<PlayerAccountData>
{
    /// <summary>Unique id of this account (it's generated by login server)</summary>
    private readonly int id;
    /// <summary>Unique name of this account</summary>
    private string name;
    /// <summary>Time of account creation, measured in milliseconds since 1.1.1970 0:00 UTC</summary>
    private long creationDate;
    /// <summary>Access level</summary>
    private sbyte accessLevel;
    /// <summary>Membership of this account</summary>
    private sbyte membership;

    private AccountTime accountTime;

    private Dictionary<int, PlayerAccountData> players = new();

    private Storage accountWarehouse;

    private int numberOfAsmos = 0;

    private int numberOfElyos = 0;

    private CharacterPasskey characterPasskey;

    private string securityToken = "";

    private string allowedHddSerial;

    private int stamps = 0;
    private PassportsList playerPassports;
    private DateTimeOffset? lastStamp;

    public string GetSecurityToken()
    {
        return securityToken;
    }

    public void SetSecurityToken(string token)
    {
        this.securityToken = token;
    }

    public Account(int id)
    {
        this.id = id;
    }

    public int GetId()
    {
        return id;
    }

    public string GetName()
    {
        return name;
    }

    public void SetName(string name)
    {
        this.name = name;
    }

    /// <returns>The account creation date, measured in milliseconds since 1.1.1970 0:00 UTC</returns>
    public long GetCreationDate()
    {
        return creationDate;
    }

    public void SetCreationDate(long creationDate)
    {
        this.creationDate = creationDate;
    }

    public AccountTime GetAccountTime()
    {
        return accountTime;
    }

    public void SetAccountTime(AccountTime accountTime)
    {
        this.accountTime = accountTime;
    }

    public sbyte GetAccessLevel()
    {
        return accessLevel;
    }

    public void SetAccessLevel(sbyte accessLevel)
    {
        this.accessLevel = accessLevel;
    }

    public sbyte GetMembership()
    {
        return membership;
    }

    public void SetMembership(sbyte membership)
    {
        this.membership = membership;
    }

    public override bool Equals(object o)
    {
        if (this == o)
        {
            return true;
        }

        if (!(o is Account))
        {
            return false;
        }

        Account account = (Account)o;

        return id == account.id;
    }

    public override int GetHashCode()
    {
        return id;
    }

    public PlayerAccountData GetPlayerAccountData(int chaOid)
    {
        return players.GetValueOrDefault(chaOid);
    }

    public void AddPlayerAccountData(PlayerAccountData accPlData)
    {
        players.TryGetValue(accPlData.GetPlayerCommonData().GetPlayerObjId(), out PlayerAccountData oldData);
        players[accPlData.GetPlayerCommonData().GetPlayerObjId()] = accPlData;
        if (oldData != null)
        {
            DecrementCountOf(oldData.GetPlayerCommonData().GetRace());
        }
        switch (accPlData.GetPlayerCommonData().GetRace())
        {
            case Race.ASMODIANS:
                numberOfAsmos++;
                break;
            case Race.ELYOS:
                numberOfElyos++;
                break;
        }
    }

    public Storage GetAccountWarehouse()
    {
        return accountWarehouse;
    }

    public void SetAccountWarehouse(Storage accountWarehouse)
    {
        this.accountWarehouse = accountWarehouse;
    }

    public CharacterPasskey GetCharacterPasskey()
    {
        if (characterPasskey == null)
            characterPasskey = new CharacterPasskey();
        return characterPasskey;
    }

    /// <summary>Returns the number of players that are on this account</summary>
    public int Size()
    {
        return players.Count;
    }

    public List<PlayerAccountData> GetPlayerAccDataList()
    {
        return new List<PlayerAccountData>(players.Values);
    }

    public IEnumerator<PlayerAccountData> GetEnumerator()
    {
        return players.Values.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public int GetNumberOf(Race race)
    {
        switch (race)
        {
            case Race.ASMODIANS:
                return numberOfAsmos;
            case Race.ELYOS:
                return numberOfElyos;
        }
        return 0;
    }

    public void DecrementCountOf(Race race)
    {
        switch (race)
        {
            case Race.ASMODIANS:
                numberOfAsmos--;
                break;
            case Race.ELYOS:
                numberOfElyos--;
                break;
        }
    }

    private long tollCount;

    public void SetToll(long toll)
    {
        tollCount = toll;
    }

    public long GetToll()
    {
        return tollCount;
    }

    public string GetAllowedHddSerial()
    {
        return allowedHddSerial;
    }

    public void SetAllowedHddSerial(string allowedHddSerial)
    {
        this.allowedHddSerial = allowedHddSerial;
    }

    public bool IsEmpty()
    {
        return numberOfAsmos == 0 && numberOfElyos == 0;
    }

    public int GetMaxPlayerLevel()
    {
        int maxLevel = 1;
        foreach (PlayerAccountData pad in players.Values)
        {
            if (pad.GetPlayerCommonData().GetLevel() > maxLevel)
            {
                maxLevel = pad.GetPlayerCommonData().GetLevel();
            }
        }
        return maxLevel;
    }

    public override string ToString()
    {
        return "Account [id=" + id + ", name=" + name + "]";
    }

    public int GetPassportStamps()
    {
        return stamps;
    }

    public void SetPassportStamps(int value)
    {
        this.stamps = value;
    }

    public void IncreasePassportStamps()
    {
        this.stamps++;
    }

    public PassportsList GetPassportsList()
    {
        return playerPassports;
    }

    public void SetPassportsList(PassportsList pp)
    {
        playerPassports = pp;
    }

    public DateTimeOffset? GetLastStamp()
    {
        return lastStamp;
    }

    public void SetLastStamp(DateTimeOffset? timestamp)
    {
        this.lastStamp = timestamp;
    }
}
