#!/bin/bash
# Writes the ChatServer config override (mycs.properties) from environment, then launches.
set -e

cat > /app/chat-server/config/mycs.properties <<EOF
# AUTO-GENERATED by the docker entrypoint from environment / .env — do not edit by hand.
database.url = jdbc:mysql://${DB_HOST:-mysql}:${DB_PORT:-3306}/aion_cs?characterEncoding=UTF-8
database.user = ${DB_USER:-root}
database.password = ${DB_PASSWORD:-aion}

# Address handed to clients; internal bind + GS bridge bind.
chatserver.network.client.connect_address = ${SERVER_HOST:-127.0.0.1}:${CHAT_CLIENT_PORT:-10241}
chatserver.network.client.socket_address = 0.0.0.0:10241
chatserver.network.gameserver.socket_address = 0.0.0.0:9021
EOF

cd /app
exec dotnet Aion.ChatServer.dll
